# Generated by Django 5.1.1 on 2024-10-07 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="recruiter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
