# Generated by Django 5.1.1 on 2024-10-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_application"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="recruiter",
        ),
        migrations.AddField(
            model_name="job",
            name="working_condition",
            field=models.CharField(
                choices=[
                    ("in_office", "In Office"),
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                ],
                default=1,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="job",
            name="company",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
