# Generated by Django 5.1.1 on 2024-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_alter_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="status",
            field=models.CharField(
                choices=[
                    ("under_review", "Under Review"),
                    ("interviewing", "Interviewing"),
                    ("rejected", "Rejected"),
                    ("hired", "Hired"),
                ],
                default="under_review",
                max_length=20,
            ),
        ),
    ]
